name: movie_night
description: A new Flutter project.
publish_to: 'none'
version: 1.2.2+5

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  uuid: ^4.2.2
  provider: ^6.0.5
  dio: ^5.5.0+1
  shared_preferences: ^2.2.0
  cached_network_image: ^3.3.0
  json_annotation: ^4.8.1
  flutter_dotenv: ^5.1.0
  go_router: ^12.1.1
  infinite_scroll_pagination: ^4.0.0
  font_awesome_flutter: ^10.6.0
  google_fonts: 6.1.0
  persistent_bottom_nav_bar: ^6.2.1
  auto_size_text: ^3.0.0
  hive: ^4.0.0-dev.2
  isar_flutter_libs: ^4.0.0-dev.13
  path_provider: ^2.1.0
  get_it: 8.0.3
  flutter_svg: ^2.0.10+1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_gen: ^5.6.0
  flutter_gen_runner: ^5.6.0
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^3.0.1
  json_serializable: ^6.7.1
  build_runner: ^2.4.7

flutter:
  uses-material-design: true

  assets:
    - lib/assets/icons/
    - lib/assets/images/
    - .env

flutter_gen:
  integrations:
    flutter_svg: true

flutter_launcher_icons:
  android: "launcher_icon"
  ios: false
  image_path: "lib/assets/movie_night_icon.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
# To reset the app icon run the following commands
# flutter clean
# flutter pub get
# dart run flutter_launcher_icons:main

# To build APK of project run
# flutter build apk --split-per-abi --obfuscate --split-debug-info=obfuscated_symbols

# To build app bundle
# flutter build appbundle --obfuscate --split-debug-info=obfuscated_symbols

# To regenerate the assets and code run the following command
# dart run build_runner build --delete-conflicting-outputs
