import 'package:movie_night/entities/movie.dart';

List<Movie> allMovies = [
  // Movie to Watch
  Movie(title: "Psicopata americano", runtime: 102, genres: ["Crime", "Drama", "Horror"], rating: 7.6, watched: false, favorite: false),
  Movie(title: "O enigma de outro mundo", runtime: 109, genres: ["Horror", "Mystery", "Sci-Fi"], rating: 8.2, watched: false, favorite: false),
  Movie(title: "Tubarão", runtime: 124, genres: ["Adventure", "Mystery", "Thriller"], rating: 8.1, watched: false, favorite: false),
  Movie(title: "Fogo contra fogo", runtime: 170, genres: ["Action", "Drama", "Crime"], rating: 8.3, watched: false, favorite: false),
  Movie(title: "Top Gun: Ases indomáveis", runtime: 109, genres: ["Action", "Drama"], rating: 6.9, watched: false, favorite: false),
  Movie(title: "Pulp Fiction - Tempo de violência", runtime: 154, genres: ["Crime", "Drama"], rating: 8.9, watched: false, favorite: false),
  Movie(title: "Os garotos perdidos", runtime: 97, genres: ["Comedy", "Horror"], rating: 7.2, watched: false, favorite: false),
  Movie(title: "Ed Wood", runtime: 127, genres: ["Biography", "Comedy", "Drama"], rating: 7.8, watched: false, favorite: false),
  Movie(title: "Vidas em jogo", runtime: 129, genres: ["Drama", "Mystery", "Thriller"], rating: 7.7, watched: false, favorite: false),
  Movie(title: "Quanto mais quente melhor", runtime: 121, genres: ["Comedy", "Music", "Romance"], rating: 8.2, watched: false, favorite: false),
  Movie(title: "Alien - o 8º Passageiro", runtime: 117, genres: ["Horror", "Sci-Fi"], rating: 8.5, watched: false, favorite: false),
  Movie(title: "O show de truman: O show da vida", runtime: 103, genres: ["Comedy", "Drama"], rating: 8.2, watched: false, favorite: false),
  Movie(title: "Uma noite alucinante: A morte do demônio", runtime: 85, genres: ["Horror"], rating: 7.4, watched: false, favorite: false),
  Movie(title: "Crepúsculo das águias", runtime: 156, genres: ["Action", "Drama", "Romance"], rating: 7.1, watched: false, favorite: false),
  Movie(title: "Carros", runtime: 117, genres: ["Animation", "Adventure", "Comedy"], rating: 7.2, watched: false, favorite: false),
  Movie(title: "Mad max: Estrada da fúria", runtime: 120, genres: ["Action", "Adventure", "Sci-Fi"], rating: 8.1, watched: false, favorite: false),
  Movie(title: "Encontros e Desencontros", runtime: 102, genres: ["Comedy", "Drama"], rating: 7.7, watched: false, favorite: false),
  Movie(title: "50%", runtime: 100, genres: ["Comedy", "Drama", "Romance"], rating: 7.6, watched: false, favorite: false),
  Movie(title: "Star Wars: Episódio IV - Uma nova esperança", runtime: 121, genres: ["Action", "Adventure", "Fantasy"], rating: 8.6, watched: false, favorite: false),
  Movie(title: "Mulher-Maravilha", runtime: 141, genres: ["Action", "Adventure", "Fantasy"], rating: 7.4, watched: false, favorite: false),
  Movie(title: "Whiplash: Em busca da perfeição", runtime: 106, genres: ["Drama", "Music"], rating: 8.5, watched: false, favorite: false),
  Movie(title: "O irlandês", runtime: 209, genres: ["Biography", "Crime", "Drama"], rating: 7.8, watched: false, favorite: false),
  Movie(title: "Os goonies", runtime: 114, genres: ["Adventure", "Comedy", "Family"], rating: 7.7, watched: false, favorite: false),
  // Movies watched
  Movie(title: "O rei leão", runtime: 88, genres: ["Animation", "Adventure", "Drama"], rating: 8.5, watched: true, favorite: false),
  Movie(title: "12 homens e uma sentença", runtime: 96, genres: ["Crime", "Drama"], rating: 9.0, watched: true, favorite: false),
  Movie(title: "Ernest & Célestine", runtime: 80, genres: ["Animation", "Adventure", "Comedy"], rating: 7.8, watched: true, favorite: false),
  Movie(title: "Os donos da rua", runtime: 112, genres: ["Crime", "Drama"], rating: 7.8, watched: true, favorite: false),
  Movie(title: "Curtindo a vida adoidado", runtime: 103, genres: ["Comedy"], rating: 7.8, watched: true, favorite: false),
  Movie(title: "Bling Ring: A gangue de hollywood", runtime: 90, genres: ["Biography", "Crime", "Drama"], rating: 5.6, watched: true, favorite: false),
  Movie(title: "Vida", runtime: 104, genres: ["Horror", "Sci-Fi", "Thriller"], rating: 6.6, watched: true, favorite: false),
  Movie(title: "O mestre invencível", runtime: 111, genres: ["Action", "Comedy"], rating: 7.4, watched: true, favorite: false),
  Movie(title: "A mosca", runtime: 96, genres: ["Drama", "Horror", "Sci-Fi"], rating: 7.6, watched: true, favorite: false),
  Movie(title: "Batman begins", runtime: 140, genres: ["Action", "Crime", "Drama"], rating: 8.2, watched: true, favorite: false),
  Movie(title: "Amnésia", runtime: 113, genres: ["Mystery", "Thriller"], rating: 8.4, watched: true, favorite: false),
  Movie(title: "O predador", runtime: 107, genres: ["Action", "Adventure", "Horror"], rating: 7.8, watched: true, favorite: false),
  // Favorite movies
  Movie(title: "Loucademia de polícia", runtime: 96, genres: ["Comedy"], rating: 6.7, watched: true, favorite: true),
  Movie(title: "Por um punhado de dólares", runtime: 99, genres: ["Action", "Drama", "Western"], rating: 7.9, watched: true, favorite: true),
  Movie(title: "Atômica", runtime: 115, genres: ["Action", "thriller"], rating: 6.7, watched: true, favorite: true),
  Movie(title: "Zootopia", runtime: 108, genres: ["Animation", "Adventure", "Comedy"], rating: 8.0, watched: true, favorite: true),
  Movie(title: "Ace Ventura: Um detetive diferente", runtime: 86, genres: ["Comedy"], rating: 6.9, watched: true, favorite: true),
  Movie(title: "Taxi Driver: Motorista de táxi", runtime: 114, genres: ["Crime", "Drama"], rating: 8.2, watched: true, favorite: true),
  Movie(title: "A caça", runtime: 115, genres: ["Drama"], rating: 8.3, watched: true, favorite: true),
  Movie(title: "Metrópolis", runtime: 153, genres: ["Drama", "Sci-Fi"], rating: 8.3, watched: true, favorite: true),
];