import 'package:movie_night/entities/movie.dart';

List<Movie> allMovies = [
  // Movie to Watch
  Movie(imdbId: "01",title: "Psicopata americano", year: 2000, runtime: 102, genres: ["Crime", "Drama", "Horror"], rating: 7.6, watched: false, favorite: false),
  Movie(imdbId: "02",title: "O enigma de outro mundo", year: 2000, runtime: 109, genres: ["Horror", "Mystery", "Sci-Fi"], rating: 8.2, watched: false, favorite: false),
  Movie(imdbId: "03",title: "Tubarão", year: 2000, runtime: 124, genres: ["Adventure", "Mystery", "Thriller"], rating: 8.1, watched: false, favorite: false),
  Movie(imdbId: "04",title: "Fogo contra fogo", year: 2000, runtime: 170, genres: ["Action", "Drama", "Crime"], rating: 8.3, watched: false, favorite: false),
  Movie(imdbId: "05",title: "Top Gun: Ases indomáveis", year: 2000, runtime: 109, genres: ["Action", "Drama"], rating: 6.9, watched: false, favorite: false),
  Movie(imdbId: "06",title: "Pulp Fiction - Tempo de violência", year: 2000, runtime: 154, genres: ["Crime", "Drama"], rating: 8.9, watched: false, favorite: false),
  Movie(imdbId: "07",title: "Os garotos perdidos", year: 2000, runtime: 97, genres: ["Comedy", "Horror"], rating: 7.2, watched: false, favorite: false),
  Movie(imdbId: "08",title: "Ed Wood", year: 2000, runtime: 127, genres: ["Biography", "Comedy", "Drama"], rating: 7.8, watched: false, favorite: false),
  Movie(imdbId: "09",title: "Vidas em jogo", year: 2000, runtime: 129, genres: ["Drama", "Mystery", "Thriller"], rating: 7.7, watched: false, favorite: false),
  Movie(imdbId: "10",title: "Quanto mais quente melhor", year: 2000, runtime: 121, genres: ["Comedy", "Music", "Romance"], rating: 8.2, watched: false, favorite: false),
  Movie(imdbId: "11",title: "Alien - o 8º Passageiro", year: 2000, runtime: 117, genres: ["Horror", "Sci-Fi"], rating: 8.5, watched: false, favorite: false),
  Movie(imdbId: "12",title: "O show de truman: O show da vida", year: 2000, runtime: 103, genres: ["Comedy", "Drama"], rating: 8.2, watched: false, favorite: false),
  Movie(imdbId: "13",title: "Uma noite alucinante: A morte do demônio", year: 2000, runtime: 85, genres: ["Horror"], rating: 7.4, watched: false, favorite: false),
  Movie(imdbId: "14",title: "Crepúsculo das águias", year: 2000, runtime: 156, genres: ["Action", "Drama", "Romance"], rating: 7.1, watched: false, favorite: false),
  Movie(imdbId: "15",title: "Carros", year: 2000, runtime: 117, genres: ["Animation", "Adventure", "Comedy"], rating: 7.2, watched: false, favorite: false),
  Movie(imdbId: "16",title: "Mad max: Estrada da fúria", year: 2000, runtime: 120, genres: ["Action", "Adventure", "Sci-Fi"], rating: 8.1, watched: false, favorite: false),
  Movie(imdbId: "17",title: "Encontros e Desencontros", year: 2000, runtime: 102, genres: ["Comedy", "Drama"], rating: 7.7, watched: false, favorite: false),
  Movie(imdbId: "18",title: "50%", year: 2000, runtime: 100, genres: ["Comedy", "Drama", "Romance"], rating: 7.6, watched: false, favorite: false),
  Movie(imdbId: "19",title: "Star Wars: Episódio IV - Uma nova esperança", year: 2000, runtime: 121, genres: ["Action", "Adventure", "Fantasy"], rating: 8.6, watched: false, favorite: false),
  Movie(imdbId: "20",title: "Mulher-Maravilha", year: 2000, runtime: 141, genres: ["Action", "Adventure", "Fantasy"], rating: 7.4, watched: false, favorite: false),
  Movie(imdbId: "21",title: "Whiplash: Em busca da perfeição", year: 2000, runtime: 106, genres: ["Drama", "Music"], rating: 8.5, watched: false, favorite: false),
  Movie(imdbId: "22",title: "O irlandês", year: 2000, runtime: 209, genres: ["Biography", "Crime", "Drama"], rating: 7.8, watched: false, favorite: false),
  Movie(imdbId: "23",title: "Os goonies", year: 2000, runtime: 114, genres: ["Adventure", "Comedy", "Family"], rating: 7.7, watched: false, favorite: false),
  // Movies watched
  Movie(imdbId: "24",title: "O rei leão", year: 2000, runtime: 88, genres: ["Animation", "Adventure", "Drama"], rating: 8.5, watched: true, favorite: false),
  Movie(imdbId: "25",title: "12 homens e uma sentença", year: 2000, runtime: 96, genres: ["Crime", "Drama"], rating: 9.0, watched: true, favorite: false),
  Movie(imdbId: "26",title: "Ernest & Célestine", year: 2000, runtime: 80, genres: ["Animation", "Adventure", "Comedy"], rating: 7.8, watched: true, favorite: false),
  Movie(imdbId: "27",title: "Os donos da rua", year: 2000, runtime: 112, genres: ["Crime", "Drama"], rating: 7.8, watched: true, favorite: false),
  Movie(imdbId: "28",title: "Curtindo a vida adoidado", year: 2000, runtime: 103, genres: ["Comedy"], rating: 7.8, watched: true, favorite: false),
  Movie(imdbId: "29",title: "Bling Ring: A gangue de hollywood", year: 2000, runtime: 90, genres: ["Biography", "Crime", "Drama"], rating: 5.6, watched: true, favorite: false),
  Movie(imdbId: "30",title: "Vida", year: 2000, runtime: 104, genres: ["Horror", "Sci-Fi", "Thriller"], rating: 6.6, watched: true, favorite: false),
  Movie(imdbId: "31",title: "O mestre invencível", year: 2000, runtime: 111, genres: ["Action", "Comedy"], rating: 7.4, watched: true, favorite: false),
  Movie(imdbId: "32",title: "A mosca", year: 2000, runtime: 96, genres: ["Drama", "Horror", "Sci-Fi"], rating: 7.6, watched: true, favorite: false),
  Movie(imdbId: "33",title: "Batman begins", year: 2000, runtime: 140, genres: ["Action", "Crime", "Drama"], rating: 8.2, watched: true, favorite: false),
  Movie(imdbId: "34",title: "Amnésia", year: 2000, runtime: 113, genres: ["Mystery", "Thriller"], rating: 8.4, watched: true, favorite: false),
  Movie(imdbId: "35",title: "O predador", year: 2000, runtime: 107, genres: ["Action", "Adventure", "Horror"], rating: 7.8, watched: true, favorite: false),
  // Favorite movies
  Movie(imdbId: "36",title: "Loucademia de polícia", year: 2000, runtime: 96, genres: ["Comedy"], rating: 6.7, watched: true, favorite: true),
  Movie(imdbId: "37",title: "Por um punhado de dólares", year: 2000, runtime: 99, genres: ["Action", "Drama", "Western"], rating: 7.9, watched: true, favorite: true),
  Movie(imdbId: "38",title: "Atômica", year: 2000, runtime: 115, genres: ["Action", "thriller"], rating: 6.7, watched: true, favorite: true),
  Movie(imdbId: "39",title: "Zootopia", year: 2000, runtime: 108, genres: ["Animation", "Adventure", "Comedy"], rating: 8.0, watched: true, favorite: true),
  Movie(imdbId: "40",title: "Ace Ventura: Um detetive diferente", year: 2000, runtime: 86, genres: ["Comedy"], rating: 6.9, watched: true, favorite: true),
  Movie(imdbId: "41",title: "Taxi Driver: Motorista de táxi", year: 2000, runtime: 114, genres: ["Crime", "Drama"], rating: 8.2, watched: true, favorite: true),
  Movie(imdbId: "42",title: "A caça", year: 2000, runtime: 115, genres: ["Drama"], rating: 8.3, watched: true, favorite: true),
  Movie(imdbId: "43",title: "Metrópolis", year: 2000, runtime: 153, genres: ["Drama", "Sci-Fi"], rating: 8.3, watched: true, favorite: true),
];